//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLFSupport.Model.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_Configuration
    {
        public int Id { get; set; }
        public string PBX_IP { get; set; }
        public int PBX_Port { get; set; }
        public string SupportEmailAddress { get; set; }
        public string Password { get; set; }
        public string SMTPHost { get; set; }
        public int SMTPPort { get; set; }
        public string MIMEHost { get; set; }
        public int MIMEPort { get; set; }
        public string SLABreachEmailAddress { get; set; }
    }
}
