//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLFSupport.Model.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_CallLog
    {
        public int CallLogId { get; set; }
        public string ExtensionNumber { get; set; }
        public string Trunk { get; set; }
        public string CallNumber { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public int Duration { get; set; }
        public byte Action { get; set; }
        public bool IsTicketGenerated { get; set; }
        public Nullable<int> TicketId { get; set; }
    
        public virtual CS_Ticket CS_Ticket { get; set; }
    }
}
