//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLFSupport.Model.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_EmailTicketLog
    {
        public int EmailTicketId { get; set; }
        public System.DateTime Date { get; set; }
        public string EmailFrom { get; set; }
        public string Description { get; set; }
        public int TicketNumber { get; set; }
    }
}
