//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLFSupport.Model.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_Log
    {
        public int LogId { get; set; }
        public string Title { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int EmployeeId { get; set; }
        public int StatusId { get; set; }
        public int TicketId { get; set; }
        public int CustumerId { get; set; }
        public string PriorityName { get; set; }
        public Nullable<int> ForwardToEmployee { get; set; }
    
        public virtual CS_Status CS_Status { get; set; }
        public virtual CS_Ticket CS_Ticket { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
