//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLFSupport.Model.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_Status
    {
        public CS_Status()
        {
            this.CS_Ticket = new HashSet<CS_Ticket>();
            this.CS_Log = new HashSet<CS_Log>();
        }
    
        public int StatusId { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<CS_Ticket> CS_Ticket { get; set; }
        public virtual ICollection<CS_Log> CS_Log { get; set; }
    }
}
