//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLFSupport.Model.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Projects = new HashSet<Projects>();
            this.CS_Ticket = new HashSet<CS_Ticket>();
            this.CS_Log = new HashSet<CS_Log>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Pincode { get; set; }
        public string PhoneNo { get; set; }
        public string FaxNo { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public int OwnerId { get; set; }
        public string ContactPersonName { get; set; }
        public bool IsActive { get; set; }
        public string CS_DedicatedNumber { get; set; }
        public string CS_DomainName { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Projects> Projects { get; set; }
        public virtual ICollection<CS_Ticket> CS_Ticket { get; set; }
        public virtual ICollection<CS_Log> CS_Log { get; set; }
        public virtual CS_CustomerEmployeeInfo CS_CustomerEmployeeInfo { get; set; }
        public virtual Country Country { get; set; }
    }
}
