//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLFSupport.Model.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Customer = new HashSet<Customer>();
            this.Employee1 = new HashSet<Employee>();
            this.Projects = new HashSet<Projects>();
            this.Projects1 = new HashSet<Projects>();
            this.Projects2 = new HashSet<Projects>();
            this.ProjectTeam = new HashSet<ProjectTeam>();
            this.CS_Ticket = new HashSet<CS_Ticket>();
            this.CS_Log = new HashSet<CS_Log>();
            this.CS_Ticket1 = new HashSet<CS_Ticket>();
            this.TimeSheet = new HashSet<TimeSheet>();
            this.ProjectActivityLink = new HashSet<ProjectActivityLink>();
            this.ProjectActivityLink1 = new HashSet<ProjectActivityLink>();
            this.ProjectPhases = new HashSet<ProjectPhases>();
            this.ProjectPhases1 = new HashSet<ProjectPhases>();
            this.Task = new HashSet<Task>();
            this.Task1 = new HashSet<Task>();
            this.EmployeeDesignation = new HashSet<EmployeeDesignation>();
            this.ProjectCR = new HashSet<ProjectCR>();
            this.ProjectDeadline = new HashSet<ProjectDeadline>();
            this.TlfmsJiraLink = new HashSet<TlfmsJiraLink>();
            this.TlfmsJiraLink1 = new HashSet<TlfmsJiraLink>();
        }
    
        public int Id { get; set; }
        public int EmployeeNr { get; set; }
        public string FiistName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PresentAddress1 { get; set; }
        public string PresentAddress2 { get; set; }
        public string PermanentAddress1 { get; set; }
        public string PermanentAddress2 { get; set; }
        public string Phone_Mobile { get; set; }
        public string Phone_Home { get; set; }
        public string Email_Official { get; set; }
        public string Email_Personal { get; set; }
        public string Skype { get; set; }
        public System.DateTime DOB { get; set; }
        public Nullable<System.DateTime> DOA { get; set; }
        public string IdentificationMark { get; set; }
        public string PAN { get; set; }
        public Nullable<bool> IsSupervisor { get; set; }
        public string PicturePath { get; set; }
        public bool IsActive { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public string AccountNr { get; set; }
        public string PassBookName { get; set; }
        public Nullable<double> LeaveOpeningBalance { get; set; }
        public Nullable<System.DateTime> LeaveBalEffectiveDate { get; set; }
        public int GenderId { get; set; }
        public Nullable<int> PresentCityId { get; set; }
        public Nullable<int> PresentStateId { get; set; }
        public Nullable<int> PresentCountryId { get; set; }
        public string PresentPincode { get; set; }
        public Nullable<int> PermanentCityId { get; set; }
        public Nullable<int> PermanentStateId { get; set; }
        public Nullable<int> PermanentCountryId { get; set; }
        public string PermanentPincode { get; set; }
        public Nullable<int> MaritalStatusId { get; set; }
        public Nullable<int> BirthCountryId { get; set; }
        public Nullable<int> SupervisorId { get; set; }
        public Nullable<int> EmploymentTypeId { get; set; }
        public Nullable<int> GradeId { get; set; }
        public Nullable<int> WorkScheduleId { get; set; }
        public Nullable<int> BankBranchId { get; set; }
        public Nullable<int> EmploymentStatusId { get; set; }
        public Nullable<int> BloodGroupId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> OfficeLocationId { get; set; }
        public Nullable<decimal> MonthlyCredit { get; set; }
        public string VoIP { get; set; }
        public bool Assignable { get; set; }
    
        public virtual ICollection<Customer> Customer { get; set; }
        public virtual ICollection<Employee> Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual ICollection<Projects> Projects { get; set; }
        public virtual ICollection<Projects> Projects1 { get; set; }
        public virtual ICollection<Projects> Projects2 { get; set; }
        public virtual ICollection<ProjectTeam> ProjectTeam { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<CS_Ticket> CS_Ticket { get; set; }
        public virtual ICollection<CS_Log> CS_Log { get; set; }
        public virtual ICollection<CS_Ticket> CS_Ticket1 { get; set; }
        public virtual ICollection<TimeSheet> TimeSheet { get; set; }
        public virtual ICollection<ProjectActivityLink> ProjectActivityLink { get; set; }
        public virtual ICollection<ProjectActivityLink> ProjectActivityLink1 { get; set; }
        public virtual ICollection<ProjectPhases> ProjectPhases { get; set; }
        public virtual ICollection<ProjectPhases> ProjectPhases1 { get; set; }
        public virtual ICollection<Task> Task { get; set; }
        public virtual ICollection<Task> Task1 { get; set; }
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual Country Country2 { get; set; }
        public virtual ICollection<EmployeeDesignation> EmployeeDesignation { get; set; }
        public virtual ICollection<ProjectCR> ProjectCR { get; set; }
        public virtual ICollection<ProjectDeadline> ProjectDeadline { get; set; }
        public virtual ICollection<TlfmsJiraLink> TlfmsJiraLink { get; set; }
        public virtual ICollection<TlfmsJiraLink> TlfmsJiraLink1 { get; set; }
    }
}
