//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLFSupport.Model.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDesignation
    {
        public int EmployeeId { get; set; }
        public int DesignationId { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public bool IsCurrent { get; set; }
        public int Id { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
