//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLFSupport.Model.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectActivityLink
    {
        public ProjectActivityLink()
        {
            this.TimeSheet = new HashSet<TimeSheet>();
        }
    
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public Nullable<int> ProjectActivityId { get; set; }
        public string ProjectActivityName { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CreatedIPAddress { get; set; }
        public string UpdatedIPAddress { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Projects Projects { get; set; }
        public virtual ICollection<TimeSheet> TimeSheet { get; set; }
        public virtual ProjectActivity ProjectActivity { get; set; }
    }
}
