//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLFSupport.Model.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectActivity
    {
        public ProjectActivity()
        {
            this.ProjectActivityLink = new HashSet<ProjectActivityLink>();
            this.TimeSheet = new HashSet<TimeSheet>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ActivityTypeId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ActivityType ActivityType { get; set; }
        public virtual ICollection<ProjectActivityLink> ProjectActivityLink { get; set; }
        public virtual ICollection<TimeSheet> TimeSheet { get; set; }
    }
}
