//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLFSupport.Model.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectResourceDemand
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public int ProjectRoleId { get; set; }
        public int ExpectedStartWeek { get; set; }
        public Nullable<int> ExpectedHoursPerWeek { get; set; }
        public int Year { get; set; }
        public Nullable<int> NoOfWeeks { get; set; }
        public string Remark { get; set; }
    
        public virtual ProjectRole ProjectRole { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
