//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLFSupport.Model.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectCR
    {
        public int CRId { get; set; }
        public int ProjectId { get; set; }
        public string CRNo { get; set; }
        public System.DateTime CRDate { get; set; }
        public string Description { get; set; }
        public decimal EstimatedHrs { get; set; }
        public bool ApprovedByClient { get; set; }
        public int ApprovedBy { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Status { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Users Users { get; set; }
        public virtual Projects Projects { get; set; }
        public virtual Projects Projects1 { get; set; }
    }
}
