//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLFSupport.Model.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectRole
    {
        public ProjectRole()
        {
            this.ProjectResourceDemand = new HashSet<ProjectResourceDemand>();
            this.ProjectTeam = new HashSet<ProjectTeam>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsAssignable { get; set; }
    
        public virtual ICollection<ProjectResourceDemand> ProjectResourceDemand { get; set; }
        public virtual ICollection<ProjectTeam> ProjectTeam { get; set; }
    }
}
