//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLFSupport.Model.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDeadline
    {
        public int Id { get; set; }
        public System.DateTime RevisedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string Reason { get; set; }
        public int ProjectId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
