//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLFSupport.Model.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public int SupportTypeId { get; set; }
        public int AssignedTo { get; set; }
        public int CreatedBy { get; set; }
        public int TaskPriorityId { get; set; }
        public Nullable<System.DateTime> DueDateTime { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LatestStatus { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
