//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLFSupport.Model.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheet
    {
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<short> WeekNo { get; set; }
        public string ReferenceIssueNo { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public Nullable<int> ProjectActivityLinkId { get; set; }
        public decimal TimeSpent { get; set; }
        public Nullable<decimal> TimeBillable { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ProjectPhaseId { get; set; }
        public Nullable<decimal> EstimatedTime { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsExtraHours { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Year { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Projects Projects { get; set; }
        public virtual ProjectActivityLink ProjectActivityLink { get; set; }
        public virtual ProjectPhases ProjectPhases { get; set; }
        public virtual ProjectActivity ProjectActivity { get; set; }
    }
}
