//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLFSupport.Model.DatabaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TLFCSEntities : DbContext
    {
        public TLFCSEntities()
            : base("name=TLFCSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CS_Priority> CS_Priority { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<ProjectTeam> ProjectTeam { get; set; }
        public virtual DbSet<CS_EmailTicketLog> CS_EmailTicketLog { get; set; }
        public virtual DbSet<CS_Status> CS_Status { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<CS_Ticket> CS_Ticket { get; set; }
        public virtual DbSet<CS_Log> CS_Log { get; set; }
        public virtual DbSet<CS_CallLog> CS_CallLog { get; set; }
        public virtual DbSet<CS_CustomerEmployeeInfo> CS_CustomerEmployeeInfo { get; set; }
        public virtual DbSet<CS_EmailLink> CS_EmailLink { get; set; }
        public virtual DbSet<ProjectGroup> ProjectGroup { get; set; }
        public virtual DbSet<ProjectStatus> ProjectStatus { get; set; }
        public virtual DbSet<Technology> Technology { get; set; }
        public virtual DbSet<ActivityType> ActivityType { get; set; }
        public virtual DbSet<Phases> Phases { get; set; }
        public virtual DbSet<TimeSheet> TimeSheet { get; set; }
        public virtual DbSet<ProjectActivityLink> ProjectActivityLink { get; set; }
        public virtual DbSet<ProjectPhases> ProjectPhases { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<CS_Configuration> CS_Configuration { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<ProjectType> ProjectType { get; set; }
        public virtual DbSet<ProjectCategory> ProjectCategory { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<EmployeeDesignation> EmployeeDesignation { get; set; }
        public virtual DbSet<ProjectActivity> ProjectActivity { get; set; }
        public virtual DbSet<ProjectCR> ProjectCR { get; set; }
        public virtual DbSet<ProjectDeadline> ProjectDeadline { get; set; }
        public virtual DbSet<ProjectResourceDemand> ProjectResourceDemand { get; set; }
        public virtual DbSet<ProjectRole> ProjectRole { get; set; }
        public virtual DbSet<TlfmsJiraLink> TlfmsJiraLink { get; set; }
        public virtual DbSet<CS_SLA> CS_SLA { get; set; }
    }
}
