//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLFSupport.Model.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Employee = new HashSet<Employee>();
            this.UserRole = new HashSet<UserRole>();
            this.ProjectCR = new HashSet<ProjectCR>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime CreateOn { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public bool IsLocked { get; set; }
    
        public virtual ICollection<Employee> Employee { get; set; }
        public virtual ICollection<UserRole> UserRole { get; set; }
        public virtual ICollection<ProjectCR> ProjectCR { get; set; }
    }
}
